FROM python:3.13-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock part1.py random_files_generator.py tree.py ./

RUN uv sync --locked

EXPOSE 8000

CMD ["uv", "run", "fastapi", "run", "part1.py"]
