FROM osixia/openldap:1.5.0

LABEL org.opencontainers.image.source=https://github.com/UnitedCTF/UnitedCTF2025

COPY bootstrap.ldif /container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
