name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      filter:
        type: string
        description: Filter images to build, omit to build everything

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Find and Build Docker Images
        run: |
          # Find all directories with docker-compose.yml or compose.yaml
          for compose_file in $(find ./ctfd ./challenges -name 'docker-compose.yml' -o -name 'docker-compose.yaml' -o -name 'compose.yml' -o -name 'compose.yaml' | grep '${{ inputs.filter }}'); do
            dir=$(dirname "$compose_file")

            echo "Building and pushing image for $dir"

            # Build the Docker image
            docker compose -f "$compose_file" build --build-arg BUILDKIT_INLINE_CACHE=1 --pull

            # Push the Docker image
            docker compose -f "$compose_file" push
          done
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
